#!/usr/bin/env node
/**
 * 从 pinyin.min.js 提取拼音字典数据并生成 Go 代码
 * 
 * 用法: node tools/extract_pinyin_dict.js
 */

const fs = require('fs');
const path = require('path');

// 文件路径
const INPUT_FILE = path.join(__dirname, '../assets/external-libs/pinyin.min.js');
const OUTPUT_DIR = path.join(__dirname, '../enhance_modules/pinyin/dict');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'dict_gen.go');
const PHRASES_OUTPUT_FILE = path.join(OUTPUT_DIR, 'phrases_gen.go');

// 确保输出目录存在
if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

console.log('📖 读取 pinyin.min.js...');
const content = fs.readFileSync(INPUT_FILE, 'utf-8');

// 提取字典数据
console.log('🔍 提取字典数据...');
const dictEntries = [];
const dictRegex = /dict\[0x([0-9A-Fa-f]+)\]\s*=\s*"([^"]+)";/g;

let match;
let count = 0;
while ((match = dictRegex.exec(content)) !== null) {
    const unicode = match[1]; // 十六进制 Unicode
    const pinyins = match[2];  // 拼音字符串
    
    dictEntries.push({
        unicode: unicode,
        decimal: parseInt(unicode, 16),
        char: String.fromCodePoint(parseInt(unicode, 16)),
        pinyins: pinyins.split(',').map(p => p.trim())
    });
    
    count++;
    if (count % 1000 === 0) {
        console.log(`  已提取 ${count} 个字符...`);
    }
}

console.log(`✅ 成功提取 ${dictEntries.length} 个汉字的拼音数据`);

// 生成 Go 代码
console.log('🔨 生成 Go 代码...');

let goCode = `// Code generated by tools/extract_pinyin_dict.js. DO NOT EDIT.
// Source: assets/external-libs/pinyin.min.js (v4.0.0)
// Generated at: ${new Date().toISOString()}
// Total entries: ${dictEntries.length}

package dict

// CharDict 汉字拼音字典
// Key: Unicode 码点 (rune)
// Value: 拼音列表 (带声调,按使用频率排序)
var CharDict = map[rune][]string{
`;

// 按 Unicode 排序以便查看
dictEntries.sort((a, b) => a.decimal - b.decimal);

// 生成字典条目
for (const entry of dictEntries) {
    const pinyinsStr = entry.pinyins.map(p => `"${p}"`).join(', ');
    const comment = ` // ${entry.char}`;
    goCode += `\t0x${entry.unicode.toUpperCase()}: {${pinyinsStr}},${comment}\n`;
}

goCode += `}\n\n`;

// 添加辅助函数和统计信息
goCode += `// DictStats 字典统计信息
var DictStats = struct {
    TotalChars      int // 总字符数
    MultiPronounced int // 多音字数量
    MaxPronounced   int // 最多读音数
}{
    TotalChars:      ${dictEntries.length},
    MultiPronounced: ${dictEntries.filter(e => e.pinyins.length > 1).length},
    MaxPronounced:   ${Math.max(...dictEntries.map(e => e.pinyins.length))},
}

// GetPinyin 获取单个汉字的拼音
func GetPinyin(char rune) ([]string, bool) {
    pinyins, exists := CharDict[char]
    return pinyins, exists
}

// HasChar 检查字符是否在字典中
func HasChar(char rune) bool {
    _, exists := CharDict[char]
    return exists
}

// IsMultiPronounced 检查是否是多音字
func IsMultiPronounced(char rune) bool {
    pinyins, exists := CharDict[char]
    return exists && len(pinyins) > 1
}
`;

// 写入文件
fs.writeFileSync(OUTPUT_FILE, goCode, 'utf-8');
console.log(`✅ 成功生成: ${OUTPUT_FILE}`);

// 生成统计报告
const stats = {
    totalChars: dictEntries.length,
    singlePronounced: dictEntries.filter(e => e.pinyins.length === 1).length,
    multiPronounced: dictEntries.filter(e => e.pinyins.length > 1).length,
    maxPronounced: Math.max(...dictEntries.map(e => e.pinyins.length)),
    maxPronouncedChar: dictEntries.find(e => 
        e.pinyins.length === Math.max(...dictEntries.map(e => e.pinyins.length))
    )
};

console.log('\n📊 字典统计:');
console.log(`  总字符数: ${stats.totalChars}`);
console.log(`  单音字: ${stats.singlePronounced} (${(stats.singlePronounced/stats.totalChars*100).toFixed(1)}%)`);
console.log(`  多音字: ${stats.multiPronounced} (${(stats.multiPronounced/stats.totalChars*100).toFixed(1)}%)`);
console.log(`  最多读音数: ${stats.maxPronounced}`);
if (stats.maxPronouncedChar) {
    console.log(`  读音最多的字: ${stats.maxPronouncedChar.char} (${stats.maxPronouncedChar.pinyins.join(', ')})`);
}

// 生成示例文件
const exampleFile = path.join(OUTPUT_DIR, 'dict_example.txt');
const examples = dictEntries.slice(0, 50).map(e => 
    `${e.char} (U+${e.unicode.toUpperCase()}): ${e.pinyins.join(', ')}`
).join('\n');

fs.writeFileSync(exampleFile, `拼音字典示例 (前50个字符)\n\n${examples}\n`, 'utf-8');
console.log(`✅ 生成示例文件: ${exampleFile}`);

// ============================================================================
// 提取词组字典 (phrases_dict)
// ============================================================================

console.log('\n\n🔍 提取词组字典 (phrases_dict)...');

const phrasesRegex = /"([^"]+)":\s*\[\s*(\[.*?\])\s*\]/g;
const phrasesSection = content.match(/const phrases_dict = \{[\s\S]*?\n  \};/);

if (!phrasesSection) {
    console.log('❌ 未找到 phrases_dict');
} else {
    const phrasesEntries = [];
    let phrasesMatch;
    let phrasesCount = 0;
    
    while ((phrasesMatch = phrasesRegex.exec(phrasesSection[0])) !== null) {
        const phrase = phrasesMatch[1];
        const pinyinsStr = phrasesMatch[2];
        
        // 解析拼音数组: [["zhōng"], ["guó"]] -> [["zhōng"], ["guó"]]
        try {
            const pinyins = JSON.parse(`[${pinyinsStr}]`);
            phrasesEntries.push({
                phrase: phrase,
                pinyins: pinyins
            });
            
            phrasesCount++;
            if (phrasesCount % 1000 === 0) {
                console.log(`  已提取 ${phrasesCount} 个词组...`);
            }
        } catch (e) {
            console.log(`  ⚠️  解析失败: ${phrase}`);
        }
    }
    
    console.log(`✅ 成功提取 ${phrasesEntries.length} 个词组`);
    
    // 生成词组字典 Go 代码
    console.log('🔨 生成词组字典 Go 代码...');
    
    let phrasesGoCode = `// Code generated by tools/extract_pinyin_dict.js. DO NOT EDIT.
// Source: assets/external-libs/pinyin.min.js (v4.0.0)
// Generated at: ${new Date().toISOString()}
// Total entries: ${phrasesEntries.length}

package dict

// PhrasesDict 词组拼音字典
// Key: 词组字符串
// Value: 每个字的拼音数组
// 用于解决多音字歧义,如 "银行" 中的 "行" 读 háng 而不是 xíng
var PhrasesDict = map[string][][]string{
`;
    
    // 保持原始顺序 (按照 pinyin.min.js 中的顺序)
    // phrasesEntries 已经按照文件中出现的顺序了,不需要重新排序
    
    for (const entry of phrasesEntries) {
        // 转义引号和反斜杠
        const phrase = entry.phrase.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
        
        // 构建拼音数组
        const pinyinsArray = entry.pinyins.map(pyGroup => {
            return '{' + pyGroup.map(py => `"${py}"`).join(', ') + '}';
        }).join(', ');
        
        phrasesGoCode += `\t"${phrase}": {${pinyinsArray}},\n`;
    }
    
    phrasesGoCode += `}\n\n`;
    
    // 添加工具函数
    phrasesGoCode += `// GetPhrasePinyin 获取词组的拼音
func GetPhrasePinyin(phrase string) ([][]string, bool) {
    pinyins, exists := PhrasesDict[phrase]
    return pinyins, exists
}

// HasPhrase 检查词组是否在字典中
func HasPhrase(phrase string) bool {
    _, exists := PhrasesDict[phrase]
    return exists
}

// PhrasesStats 词组字典统计
var PhrasesStats = struct {
    TotalPhrases int // 总词组数
    MaxLength    int // 最长词组字数
}{
    TotalPhrases: ${phrasesEntries.length},
    MaxLength:    ${Math.max(...phrasesEntries.map(e => e.phrase.length))},
}
`;
    
    // 写入文件
    fs.writeFileSync(PHRASES_OUTPUT_FILE, phrasesGoCode, 'utf-8');
    console.log(`✅ 成功生成: ${PHRASES_OUTPUT_FILE}`);
    
    // 词组统计
    const phrasesStats = {
        total: phrasesEntries.length,
        twoChar: phrasesEntries.filter(e => e.phrase.length === 2).length,
        threeChar: phrasesEntries.filter(e => e.phrase.length === 3).length,
        fourChar: phrasesEntries.filter(e => e.phrase.length === 4).length,
        moreThanFour: phrasesEntries.filter(e => e.phrase.length > 4).length,
        maxLength: Math.max(...phrasesEntries.map(e => e.phrase.length)),
        examples: phrasesEntries.slice(0, 10)
    };
    
    console.log('\n📊 词组字典统计:');
    console.log(`  总词组数: ${phrasesStats.total}`);
    console.log(`  二字词: ${phrasesStats.twoChar} (${(phrasesStats.twoChar/phrasesStats.total*100).toFixed(1)}%)`);
    console.log(`  三字词: ${phrasesStats.threeChar} (${(phrasesStats.threeChar/phrasesStats.total*100).toFixed(1)}%)`);
    console.log(`  四字词: ${phrasesStats.fourChar} (${(phrasesStats.fourChar/phrasesStats.total*100).toFixed(1)}%)`);
    console.log(`  更长词: ${phrasesStats.moreThanFour} (${(phrasesStats.moreThanFour/phrasesStats.total*100).toFixed(1)}%)`);
    console.log(`  最长词组: ${phrasesStats.maxLength} 字`);
    
    // 生成词组示例文件
    const phrasesExampleFile = path.join(OUTPUT_DIR, 'phrases_example.txt');
    const phrasesExamples = phrasesStats.examples.map(e => 
        `${e.phrase}: ${e.pinyins.map(py => py.join('')).join(' ')}`
    ).join('\n');
    
    fs.writeFileSync(phrasesExampleFile, `词组字典示例 (前10个)\n\n${phrasesExamples}\n`, 'utf-8');
    console.log(`✅ 生成示例文件: ${phrasesExampleFile}`);
}

console.log('\n\n🎉 字典提取完成!');
console.log('\n下一步:');
console.log('  1. cd enhance_modules/pinyin/dict');
console.log('  2. go fmt *.go');
console.log('  3. 编译测试: go build');

